name: amp-composer-debug
recipe: wordpress
config:
  php: '7.4'
  via: nginx
  webroot: web
  database: mariadb

tooling:
  setup-wp:
    service: appserver
    cmd: bash /app/bin/setup.sh
  install-amp:
    service: appserver
    cmd: bash /app/bin/install.sh
